version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/
    overwrite: yes

hooks:
  ApplicationStart:
    - location: scripts/stop.sh
      runas: root
    - location: scripts/deploy.sh
      timeout: 60
      runas: root