server:
  port: 80

spring:
  application:
    name: SPRING-TRICOUNT
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/tricountapi-db
    username: tricountapi
    password:
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework.jdbc: debug


